server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_system?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mysql.20231002
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.liaoyun.domain
  configuration:
    map-underscore-to-camel-case: true

